name: Build

on:
  pull_request:
    branches: [ master, dev/*, feature/* ]
  push:
    branches: [ master, dev/*, feature/* ]
    
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
    strategy:
      matrix:
        config:
          - name: "Windows Latest MinGW"
            os: windows-latest
            cc: "gcc"
            cxx: "g++"
          - name: "Ubuntu Latest GCC"
            os: ubuntu-latest
            cc: "gcc"
            cxx: "g++"
          - name: "macOS Latest Clang"
            os: macos-latest
            cc: "clang"
            cxx: "clang++"

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
